### ISSUE TITLE
the typeKey doesn't actually do the actions.

### ISSUE THREAD

**Issue by obvkoen** [d4n5h/Duckuino#11]
if there is an "typeKey(KEY_RETURN);" it doesn't do the enter

**Comment by d4n5h** [comment]
@StroopKoekje Can you please share the full code here?

**Comment by d4n5h** [comment]
@StroopKoekje I'm closing this issue, if you can elaborate further and add more details then it will be great. Thanks.

**Comment by looCiprian** [comment]
Hi! Same for me. I think it should be replaced with Keyboard.press(KEY_ENTER) (tested on Mac OS)
