### ISSUE TITLE
The typeKey doesn't work properly

### ISSUE THREAD

**Issue by looCiprian** [d4n5h/Duckuino#12]
Hi!. I think that typeKey should be replaced with Keyboard.press(KEY_ENTER) (tested on Mac OS)

_Originally posted by @looCiprian in https://github.com/d4n5h/Duckuino/issues/11#issuecomment-954048859_

**Comment by d4n5h** [comment]
Fixed in https://github.com/d4n5h/Duckuino/commit/0feae141f04c0de5f44ff4f97122d2fc2a9cb535
