### ISSUE TITLE
Kinda page freezing

### ISSUE THREAD

**Issue by lowlevl** [d4n5h/Duckuino#5]
'CTRL ALT DOWNARROW' freezes the pages for ~3sec, and outputs the code without the key combo.

**Comment by d4n5h** [comment]
Yes, key combos of more than two keys will freeze the compiler:
https://github.com/DanielShlomo/Duckuino/issues/3

I'm working on fixing it.

**Comment by lowlevl** [comment]
Do u have an email so we can talk about improvement of our projects ?
Because a got some questions and i think issues are not the way to ask ^^

2016-09-17 14:00 GMT+02:00 Daniel Shlomo notifications@github.com:

**Comment by lowlevl** [comment]
Got a best idea ^^ : Follow this, https://hack.chat/?7enuwxd0

**Comment by d4n5h** [comment]
Fixed :)
