### ISSUE TITLE
ALT F2

### ISSUE THREAD

**Issue by sigmamale1980** [d4n5h/Duckuino#7]
console Error: Unknown command or key 'F2' at line: 2. ---> any guesses? 

it was running fine til your update an hour ago.

**Comment by d4n5h** [comment]
Yes i've moved to Thecakegist compiler,
I didn't notice it has this bug...
I will revert back to mine... Just a sec.

**Comment by sigmamale1980** [comment]
cool .. good work by the way .. keep it up.

**Comment by d4n5h** [comment]
@EchoUnderscoreNine Thanks!
Done.

**Comment by sigmamale1980** [comment]
Thank you .. works like a charm now.

**Comment by d4n5h** [comment]
@EchoUnderscoreNine 
I think it is still an issue, because F2 needs to be a key and not a string.
I need to add support for F-keys

**Comment by d4n5h** [comment]
Fixed it.
And i think that i'll move back to Thecakegit's compiler and add F-keys

**Comment by sigmamale1980** [comment]
I think you`ve got a point i`m guessing its a matter of defining keyboard layout somehow to recognize F-... as a key as earlier was just a temp solution.

**Comment by d4n5h** [comment]
Try it now i've added the keys

**Comment by sigmamale1980** [comment]
odd, works better .. compiled even faster .. great!
